# Generated by Django 5.0.6 on 2024-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_link',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
